### ISSUE TITLE
Where is the full article?

### ISSUE THREAD

**Issue by donghaiwang** [ppriyank/Video-Person-Re-ID-Fantastic-Techniques-and-Where-to-Find-Them#2]
Where is the full article except the 2 Page (Student Abstract) ?

**Comment by ppriyank** [comment]
Well because of a silly mistake, our 8 pages entry for the conference was rejected. I will soon be making my entire thesis on this topic public :)

**Comment by donghaiwang** [comment]
Ok, I'm looking forward to it.
